"""
Compiler package.

Public API:
    compile_app(app_class, target, output_dir) — build production output
    discover_app(module_path)                  — import module + find App
    build_ir_tree(app_class)                   — build intermediate representation
"""

from pathlib import Path
from typing import TYPE_CHECKING

from pyui.compiler.discovery import discover_app
from pyui.compiler.ir import IRNode, IRPage, IRTree, build_ir_node, build_ir_page, build_ir_tree

if TYPE_CHECKING:
    from pyui.app import App


def _write_launcher(app_class: "type[App]", out: Path, target: str) -> None:
    """
    Write a self-contained launcher script for desktop or CLI targets.

    Produces:
      dist/run.py        — execute with `python run.py`
      dist/README.txt    — instructions
    """
    import inspect
    import shutil

    # Find the source file that defines the App class
    try:
        source_file = Path(inspect.getfile(app_class)).resolve()
    except (TypeError, OSError):
        source_file = None

    app_name = app_class.__name__
    module_stem = source_file.stem if source_file else "app"

    if target == "desktop":
        runner_import = "from pyui.renderers.desktop import run_desktop_app"
        runner_call = f"run_desktop_app({app_name})"
        run_cmd = "python run.py"
        description = "Opens a native desktop window."
    else:  # cli
        runner_import = "from pyui.renderers.cli import run_cli_app"
        runner_call = f"run_cli_app({app_name})"
        run_cmd = "python run.py"
        description = "Renders the app in the terminal."

    # Copy the app source file into dist/ so run.py can import it
    if source_file and source_file.exists():
        dest = out / source_file.name
        if dest.resolve() != source_file:
            shutil.copy2(source_file, dest)

    launcher = f"""\
#!/usr/bin/env python3
\"\"\"
PyUI {target.title()} launcher — generated by `pyui build --target {target}`.
Run with: {run_cmd}
\"\"\"
import sys
from pathlib import Path

# Ensure the app module is importable
sys.path.insert(0, str(Path(__file__).parent))

from {module_stem} import {app_name}  # noqa: E402
{runner_import}  # noqa: E402

if __name__ == "__main__":
    {runner_call}
"""

    readme = f"""\
PyUI Build — {target.title()} Target
=====================================

App     : {app_name}
Target  : {target}
Action  : {description}

Run
---
    python run.py

Requirements
------------
    pip install pyui-framework
"""

    (out / "run.py").write_text(launcher, encoding="utf-8")
    (out / "README.txt").write_text(readme, encoding="utf-8")


def compile_app(
    app_class: "type[App]",
    target: str = "web",
    output_dir: str = "./dist",
) -> Path:
    """
    Compile *app_class* for *target* and write output to *output_dir*.

    Parameters
    ----------
    app_class : type[App]
        The App subclass to compile.
    target : str
        ``"web"``, ``"desktop"``, or ``"cli"``.
    output_dir : str
        Directory to write the compiled output to.

    Returns
    -------
    Path
        The resolved output directory path.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Load plugins before compiling
    from pyui.plugins.loader import load_plugins

    plugins = load_plugins(app_class)

    if target == "web":
        from pyui.renderers.web.generator import WebGenerator

        ir = build_ir_tree(app_class)
        for p in plugins:
            p.on_compile_end(ir)
        gen = WebGenerator(ir)
        gen.write_to_disk(out)
        for p in plugins:
            p.on_build(out)

    elif target == "desktop":
        _write_launcher(app_class, out, target="desktop")

    elif target == "cli":
        _write_launcher(app_class, out, target="cli")

    else:
        raise NotImplementedError(
            f"Target '{target}' is not yet implemented. Available targets: 'web', 'desktop', 'cli'."
        )

    return out


__all__ = [
    "compile_app",
    "discover_app",
    "build_ir_node",
    "build_ir_page",
    "build_ir_tree",
    "IRNode",
    "IRPage",
    "IRTree",
]
